version: '3'


services:

  nginx:
    image: nginx:latest
    container_name: server-nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  php-fpm:
    build: ./docker/php7
    container_name: php
    links:
      - mysql

    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOSTNAME=mysql
      - DB_DATABASE=alfa
      - DB_USERNAME=root
      - DB_PASSWORD=root

    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:${DATABASE_VERSION}
    container_name: mysql
    ports:
      - 3306:3306
    environment:      
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD:  ${DATABASE_PASSWORD} 
    volumes:
      - my-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
        - 8888:80
    environment:
        PMA_HOST: mysql

volumes:
  my-data: